apiVersion: v1
description: High Performance Object Storage
name: minio
version: 6.0.3
appVersion: RELEASE.2025-10-15T17-29-55Z
keywords:
  - minio
  - storage
  - object-storage
  - s3
  - cluster
sources:
  - https://github.com/holysoles/minio-helm
maintainers:
  - name: holysoles
    url: https://github.com/holysoles
